# Generated by Django 4.1.2 on 2022-11-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField(default=0)),
                ('email', models.CharField(default='@gmail.com', max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('passportnumber', models.BigIntegerField(default=0)),
                ('profile_photo', models.ImageField(max_length=300, upload_to='profile/')),
                ('passport_expiry_date', models.DateField(default='dd-mm-yyyy')),
            ],
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserExtra',
        ),
    ]
