# Generated by Django 4.1.2 on 2022-11-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_member_remove_userextra_user_delete_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user_type',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
